### ISSUE TITLE
Plugin hooks should be exported as constants

### ISSUE THREAD

**Issue by ifeanyiisitor** [Financial-Times/dotcom-page-kit#117]
At the moment, plugins are exposing the raw hook value. This is undesirable because it promotes a level of coupling that we don't want. We are yet to come up with a proper format for hooks, which means that it is possible that their values can eventually change. So rather than saying in documentation that a developer should bind to the hook `webpackConfig::cssRule` for instance, we should instead be saying that the developer should bind to the constant `CSS_RULE`.

```js
import { hooks } from 'anvil-plugin'

export default ({ on }) => {
  on(hooks.CSS_RULE, addCssModulesSupport)
}

function addCssModulesSupport() { ... }
```

That way, if we decide to standardise on the format of hooks later on, it does not become a breaking change.

**Why don't we then just make the hook format as simple as 'cssRule', so that we don't have this issue?**

There are reasons why we would want to add more tokens to the hook. For instance, we may want to add the plugin name to the hook so that one can easily tell which plugin is responsible for the hook when one debugs in the console. By using constants, we can keep things simple for the plugin developer (as he or she won't have to be concerned about the format of hooks in order to extend the system), while also allowing for the necessary room to change. Using constants also helps us to defer the decision as to what the hook format should be.

## TODO

- [x] CLI build tool (fixed in #296)
- [x] esnext plugin (fixed in #312)
- [x] FT JS plugin (fixed in #318)
