### ISSUE TITLE
Upgrade apps to Page Kit v0.7

### ISSUE THREAD

**Issue by andygout** [Financial-Times/dotcom-page-kit#794]
#### Migration guide
https://github.com/Financial-Times/dotcom-page-kit/wiki/Upgrading-from-0.6.x-to-0.7.x

#### Progress spreadsheet (should also be updated as we go along)
https://docs.google.com/spreadsheets/d/1wOp6suvluEVmD3v8GEmP5jXRzoSpUazSN4G5HHdpQY0/edit?ts=5e173179#gid=0

#### TODO:
- `next-static` (Platforms)
  - [x] https://github.com/Financial-Times/next-static/pull/139
- `next-search-page` (Content Discovery)
  - [x] https://github.com/Financial-Times/next-search-page/pull/383
- `next-video-page` (Content Innovation)
  - [ ] https://github.com/Financial-Times/next-video-page/tree/upgrade-page-kit - appContext: Blocked by https://github.com/Financial-Times/dotcom-page-kit/pull/799
- `next-errors` (Platforms)
  - [x] https://github.com/Financial-Times/next-errors/pull/200
- `next-epaper` (Content Innovation)
  - [x] https://github.com/Financial-Times/next-epaper/pull/99
- `next-tour-page` (Acquisition)
  - [x] https://github.com/Financial-Times/next-tour-page/pull/269
- `next-graphics-page` (Content Innovation)
  - [x] https://github.com/Financial-Times/next-graphics-page/pull/255
- `next-profile` (Accounts)
  - [x] https://github.com/Financial-Times/next-profile/pull/380
- `next-syn-list` (Accounts)
  - [x] https://github.com/Financial-Times/next-syn-list/pull/102
- `next-product` (Acquisition)
  - [x] https://github.com/Financial-Times/next-product/pull/882
- `next-retention` (Accounts)
  - [x] https://github.com/Financial-Times/next-retention/pull/423
- `next-subscribe` (Acquisition)
  - [x] https://github.com/Financial-Times/next-subscribe/pull/1055
- `next-stream-page` (Content Discovery)
  - [x] https://github.com/Financial-Times/next-stream-page/pull/2405
- `next-front-page` (Content Discovery)
  - [x] https://github.com/Financial-Times/next-front-page/pull/2321
- `next-myft-page` (Content Discovery)
  - [x] https://github.com/Financial-Times/next-myft-page/pull/2269
- `next-article` (Content Innovation)
  - [x] https://github.com/Financial-Times/next-article/pull/3770
- `next-control-centre` (Ads & Privacy)
  - [x] https://github.com/Financial-Times/next-control-centre/pull/138

**Comment by andygout** [comment]
Completed!
